### ISSUE TITLE
Why not use multiple containers?

### ISSUE THREAD

**Issue by miloskroulik** [geops/cartaro-docker#1]
I don't understand, why this is a single image, instead of combination of multiple images for specific services, which are needed for Cartaro. What's the specific reason?

**Comment by trendels** [comment]
Hi miloskroulik,
you are correct, this is not the exactly the "true docker way" to set things up. However, this image is mainly intended for people who want to try out Cartaro without having to go through the manual installation process. To get them up and running as quickly as possible, we feel a single container that works out of the box, with minimal effort, is the best approach.

Experienced Docker users who want to run a Docker-Based Cartaro instance in production would indeed be better off with a separate container for each service. However, we do not provide such a setup at this time. Though hopefully, this Dockerfile can serve as a starting point for building your own containers.
